### ISSUE TITLE
Submodule cloning error

### ISSUE THREAD

**Issue by vsg-dev** [larso0/vmgpu#2]
When I followed the cloning suggestion in the root README.md I get a git error report.  I'm using Kubuntu 18.04, git --version 2.17.1.  Any ideas in what might be amiss?

$ git clone --recurse-submodules https://github.com/larso0/vmgpu.git vmgpu
Cloning into 'vmgpu'...
remote: Enumerating objects: 660, done.
remote: Total 660 (delta 0), reused 0 (delta 0), pack-reused 660
Receiving objects: 100% (660/660), 120.61 KiB | 186.00 KiB/s, done.
Resolving deltas: 100% (458/458), done.
Submodule 'bp' (git@github.com:larso0/bp.git) registered for path 'bp'
Cloning into '/home/robert/3rdParty/vmgpu/bp'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:larso0/bp.git' into submodule path '/home/robert/3rdParty/vmgpu/bp' failed
Failed to clone 'bp'. Retry scheduled
Cloning into '/home/robert/3rdParty/vmgpu/bp'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:larso0/bp.git' into submodule path '/home/robert/3rdParty/vmgpu/bp' failed
Failed to clone 'bp' a second time, aborting

**Comment by larso0** [comment]
I updated .gitmodules to point to the relative path to the bp repo instead of the ssh. Should work now with the latest commit.

**Comment by vsg-dev** [comment]
Thanks, checking out fine now :-)
