### ISSUE TITLE
Include support for VK external memory host extension?

### ISSUE THREAD

**Issue by oscarbg** [larso0/vmgpu#3]
Hi,
on your article you mention this extension should provide improved performance and now is supported on Nvidia even on Linux driver (with latest beta driver)..
do you plan on working to make use of it.. on this codebase?

**Comment by larso0** [comment]
I currently have no plans for working more on this codebase. I haven't worked on this (other than adjusting readme, etc) since 2018. Mostly keeping this repo here so people interrested have access to the code used for the paper, and my master thesis.

**Comment by oscarbg** [comment]
thanks for answer.. makes sense..
